import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <html lang="en">
      <body className={"max-w-[1440px]]"} >
      <div className={""}>
              <Navbar/>
              <div >
                  {children}
              </div>
          </div>


      </body>
    </html>
  );
}
