import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import {SessionProvider} from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <html lang="en">
      <body className={"max-w-[1440px]]"} >
      <div className={""}>
              <Navbar/>
              <div >
                  <SessionProvider>
                      {children}
                  </SessionProvider>
              </div>
          </div>


      </body>
    </html>
  );
}
