import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={"max-w-[1440px]]"}>
          <div className={""}>
            <Navbar />
            <div>{children}</div>
          </div>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
